language: python
sudo: required
services:
 - docker
before_script:
 - docker-compose up -d --build --force-recreate
 - docker-compose exec stackstorm st2ctl reload --register-all
 - docker-compose exec stackstorm st2 run packs.setup_virtualenv packs=arteria

script:
 - docker-compose exec stackstorm st2-run-pack-tests -p /opt/stackstorm/packs/arteria